### ISSUE TITLE
Experimental design table and mzXML to mzML converter

### ISSUE THREAD

**Issue by montmasis** [alexandrovteam/LCMS#7] opened 2017-11-08 16:18 UTC
Hello!

I am a new user and I started using the latest 1.5 release.  
Is it correct that the Experimental design table which is created automatically does not report the whole path of the samples in the first column, but only the file name? KNIME did not find the files, and after I edited the table manually inserting the path now it seems to retrieve it. 

I also had another error, where it said the files (mzXML) could not be converted (into mzML).
I tried to convert them with Pwiz MSConverter, but now KNIME says there was some error in the mzML format.

Thank you for the thorough documentation, but unfortunately I did not find any of these issues reported.

**Comment by iprotsyuk** [comment] 2017-11-08 16:34
Hi @montmasis,

Thanks for using Optimus :)

Concerning file names format in the experimental design table: indeed, it should keep relative file paths instead of absolute ones. It's done mainly to promote reproducibility of the analysis for cases when one shares an LC-MS dataset with 3rd parties. If the experimental design table contains absolute paths, everyone would have to fix it manually according to the dataset location on their computers. However, there's a restriction, which you've stumbled upon, that the experimental design file should be kept in the same directory, where it was initially created, since the file paths are computed relatively to that location. I'd suggest to generate experimental design in the same directory as the input files are or somewhere close to it in the folders hirerarchy using the node `Where to save template of
experimental design`. With this approach, you'll be able to just archive the whole directory and send it to anyone willing to repeat your analysis.

As for the failure at mzXML conversion step, I can't say much. Normally, this format works fine. If you share with me a few files that are causing the error, I'll try to find the problem.

Ivan

**Comment by montmasis** [comment] 2017-11-09 06:57
Think you Ivan.
Good to know. I will work on it again today. If I still don't manage I can
send you a couple of mzXML files. Any preference for sharing?

The workflow seems pretty straightforward, with the tutorial and
documentation very well done... But somehow it didn't go through. After
several attempts I decided to ask you.

**Comment by iprotsyuk** [comment] 2017-11-14 23:44
@montmasis, I'm closing the issue for the time being as the issues got resolved. Feel free to reopen it later or create a new one.

**Closed as completed by iprotsyuk** 2017-11-14 23:44 UTC
